Vagrant.configure("2") do |config|
  (1..1).each do |i|
    config.vm.define "node-#{i}" do |node|
      #node.vm.box = "centos/7"
      node.vm.box = "fedora/24-cloud-base"

      node.vm.hostname = "node-#{i}"

      config.vm.provider "virtualbox" do |v|
        v.memory = 8192
        v.cpus = 2
      end

      # TODO: this is fuckin gross, proper fix is DNS
      node.vm.network "private_network", ip: "10.0.0.20#{i}"
      node.vm.network "public_network", mac: "5CA1AB1E000#{i}"

      node.persistent_storage.enabled = true
      config.persistent_storage.use_lvm = false
      node.persistent_storage.location = "/mnt/raid/virtual/discs/node-#{i}.vdi"
      node.persistent_storage.size = 100000
      node.persistent_storage.mountname = 'spam'
      node.persistent_storage.filesystem = 'ext4'
      node.persistent_storage.mountpoint = '/spam'
      node.persistent_storage.volgroupname = 'spam'


      config.vm.provision "file", source: "/home/meatwad/prog/src/hdfs-playground/bot", destination: "/tmp/spam"
      config.vm.provision "shell", inline: "sudo bash /vagrant/bootstrap.sh"
      config.vm.provision "shell", inline: "sudo bash /vagrant/start_services.sh"
    end
  end
end
