
# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi


## add SCALA to path
export PATH=$PATH:/opt/scala/bin

## add SPARK to path
export SPARK_HOME=/usr/java/spark
export PATH=$PATH:/opt/spark/bin

## JAVA env variables
export JAVA_HOME=/usr/java/default
export PATH=$PATH:$JAVA_HOME/bin
export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar

## HADOOP env variables
export HADOOP_HOME=/opt/hadoop
export HADOOP_COMMON_HOME=$HADOOP_HOME
export HADOOP_HDFS_HOME=$HADOOP_HOME
export HADOOP_MAPRED_HOME=$HADOOP_HOME
export HADOOP_YARN_HOME=$HADOOP_HOME
export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib/native"
export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
export PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bin

## ZOOKEEPER variables
export ZOOKEEPER_HOME=/opt/zookeeper
export PATH=$PATH:$ZOOKEEPER_HOME/bin

## HBASE variables
export HBASE_HOME=/opt/hbase
export PATH=$PATH:$HBASE_HOME/bin

## KAFKA variables
export KAFKA_HOME=/opt/hbase
export PATH=$PATH:$KAFKA_HOME/bin

export KAFKA_HEAP_OPTS="-Xmx256M -Xms128M"
